### ISSUE TITLE
release tool "out of heap space" failure

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/github-release-scripts#149]
https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8197/
```
Uploading OpenJDK11U-debugimage_x64_mac_hotspot_11.0.23_2-ea.tar.gz.json
Uploading OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.23_2-ea.json.sig
Uploading OpenJDK11U-testimage_s390x_linux_hotspot_11.0.23_2-ea.tar.gz
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
```

**Comment by andrew-m-leonard** [comment]
After much debugging, found the correct way of setting the gradle application JVM options via the Application plugin settings in the build.gradle
It does however need a large 2g heap to succeed for the failing jdk11u publishes.
